---
name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: "22.2.6"
          elixir-version: "1.10.3"
      - run: mix deps.get
      - run: mix coveralls
